2024-07-15 15:55:13.492 WARNING fixture:conftest.py:60: Process started
2024-07-15 15:55:13.493 INFO fixture:conftest.py:61: Process ongoing..
2024-07-15 15:55:13.497 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.address`.
2024-07-15 15:55:13.500 DEBUG faker.factory:factory.py:95: Provider `faker.providers.address` has been localized to `en_US`.
2024-07-15 15:55:13.500 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.automotive`.
2024-07-15 15:55:13.501 DEBUG faker.factory:factory.py:95: Provider `faker.providers.automotive` has been localized to `en_US`.
2024-07-15 15:55:13.502 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.bank`.
2024-07-15 15:55:13.503 DEBUG faker.factory:factory.py:86: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2024-07-15 15:55:13.503 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.barcode`.
2024-07-15 15:55:13.503 DEBUG faker.factory:factory.py:95: Provider `faker.providers.barcode` has been localized to `en_US`.
2024-07-15 15:55:13.504 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.color`.
2024-07-15 15:55:13.504 DEBUG faker.factory:factory.py:95: Provider `faker.providers.color` has been localized to `en_US`.
2024-07-15 15:55:13.504 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.company`.
2024-07-15 15:55:13.505 DEBUG faker.factory:factory.py:95: Provider `faker.providers.company` has been localized to `en_US`.
2024-07-15 15:55:13.505 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2024-07-15 15:55:13.505 DEBUG faker.factory:factory.py:95: Provider `faker.providers.credit_card` has been localized to `en_US`.
2024-07-15 15:55:13.506 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.currency`.
2024-07-15 15:55:13.506 DEBUG faker.factory:factory.py:95: Provider `faker.providers.currency` has been localized to `en_US`.
2024-07-15 15:55:13.506 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.date_time`.
2024-07-15 15:55:13.508 DEBUG faker.factory:factory.py:95: Provider `faker.providers.date_time` has been localized to `en_US`.
2024-07-15 15:55:13.510 DEBUG faker.factory:factory.py:106: Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.510 DEBUG faker.factory:factory.py:106: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.511 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.geo`.
2024-07-15 15:55:13.511 DEBUG faker.factory:factory.py:95: Provider `faker.providers.geo` has been localized to `en_US`.
2024-07-15 15:55:13.511 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.internet`.
2024-07-15 15:55:13.512 DEBUG faker.factory:factory.py:95: Provider `faker.providers.internet` has been localized to `en_US`.
2024-07-15 15:55:13.513 DEBUG faker.factory:factory.py:106: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.513 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.job`.
2024-07-15 15:55:13.514 DEBUG faker.factory:factory.py:95: Provider `faker.providers.job` has been localized to `en_US`.
2024-07-15 15:55:13.514 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.lorem`.
2024-07-15 15:55:13.515 DEBUG faker.factory:factory.py:95: Provider `faker.providers.lorem` has been localized to `en_US`.
2024-07-15 15:55:13.515 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.misc`.
2024-07-15 15:55:13.515 DEBUG faker.factory:factory.py:95: Provider `faker.providers.misc` has been localized to `en_US`.
2024-07-15 15:55:13.515 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.passport`.
2024-07-15 15:55:13.515 DEBUG faker.factory:factory.py:95: Provider `faker.providers.passport` has been localized to `en_US`.
2024-07-15 15:55:13.516 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.person`.
2024-07-15 15:55:13.517 DEBUG faker.factory:factory.py:95: Provider `faker.providers.person` has been localized to `en_US`.
2024-07-15 15:55:13.517 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2024-07-15 15:55:13.518 DEBUG faker.factory:factory.py:95: Provider `faker.providers.phone_number` has been localized to `en_US`.
2024-07-15 15:55:13.519 DEBUG faker.factory:factory.py:106: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.519 DEBUG faker.factory:factory.py:106: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.519 DEBUG faker.factory:factory.py:106: Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.519 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.ssn`.
2024-07-15 15:55:13.520 DEBUG faker.factory:factory.py:95: Provider `faker.providers.ssn` has been localized to `en_US`.
2024-07-15 15:55:13.520 DEBUG faker.factory:factory.py:106: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-07-15 15:55:13.521 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-07-15 15:55:13.942 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "POST /backend/api/deal/create-with-client HTTP/1.1" 200 None
2024-07-15 15:55:13.942 CRITICAL root:helpers_api.py:27: ___response code- 200
2024-07-15 15:55:13.943 CRITICAL root:helpers_api.py:28: ___response body- {'deal_id': 5182}
2024-07-15 15:55:13.945 DEBUG tests_api.utils.logger:logger.py:23: > PATCH https://dev.agentum.pro/backend/api/notification/mark-all-as-read {'method': 'PATCH', 'url': 'https://dev.agentum.pro/backend/api/notification/mark-all-as-read', 'headers': {'Authorization': 'Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz'}, 'json': None}
2024-07-15 15:55:13.946 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-07-15 15:55:14.251 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "PATCH /backend/api/notification/mark-all-as-read HTTP/1.1" 200 None
2024-07-15 15:55:14.252 DEBUG tests_api.utils.logger:logger.py:27: < 200 https://dev.agentum.pro/backend/api/notification/mark-all-as-read 
2024-07-15 15:55:14.252 DEBUG tests_api.utils.logger:logger.py:35: curl -X PATCH -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz' -H 'Connection: keep-alive' -H 'Content-Length: 0' -H 'User-Agent: python-requests/2.31.0' https://dev.agentum.pro/backend/api/notification/mark-all-as-read
2024-07-15 15:55:14.256 INFO fixture:conftest.py:63: Process ended