2024-09-10 05:15:02.454 INFO page_ 1:conftest.py:34: new page opened: [<Page url='about:blank'>]
2024-09-10 05:15:02.465 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.address`.
2024-09-10 05:15:02.466 DEBUG faker.factory:factory.py:95: Provider `faker.providers.address` has been localized to `en_US`.
2024-09-10 05:15:02.467 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.automotive`.
2024-09-10 05:15:02.469 DEBUG faker.factory:factory.py:95: Provider `faker.providers.automotive` has been localized to `en_US`.
2024-09-10 05:15:02.470 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.bank`.
2024-09-10 05:15:02.472 DEBUG faker.factory:factory.py:86: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2024-09-10 05:15:02.472 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.barcode`.
2024-09-10 05:15:02.473 DEBUG faker.factory:factory.py:95: Provider `faker.providers.barcode` has been localized to `en_US`.
2024-09-10 05:15:02.473 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.color`.
2024-09-10 05:15:02.474 DEBUG faker.factory:factory.py:95: Provider `faker.providers.color` has been localized to `en_US`.
2024-09-10 05:15:02.475 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.company`.
2024-09-10 05:15:02.476 DEBUG faker.factory:factory.py:95: Provider `faker.providers.company` has been localized to `en_US`.
2024-09-10 05:15:02.476 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2024-09-10 05:15:02.476 DEBUG faker.factory:factory.py:95: Provider `faker.providers.credit_card` has been localized to `en_US`.
2024-09-10 05:15:02.477 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.currency`.
2024-09-10 05:15:02.477 DEBUG faker.factory:factory.py:95: Provider `faker.providers.currency` has been localized to `en_US`.
2024-09-10 05:15:02.477 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.date_time`.
2024-09-10 05:15:02.479 DEBUG faker.factory:factory.py:95: Provider `faker.providers.date_time` has been localized to `en_US`.
2024-09-10 05:15:02.479 DEBUG faker.factory:factory.py:106: Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.479 DEBUG faker.factory:factory.py:106: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.480 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.geo`.
2024-09-10 05:15:02.480 DEBUG faker.factory:factory.py:95: Provider `faker.providers.geo` has been localized to `en_US`.
2024-09-10 05:15:02.480 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.internet`.
2024-09-10 05:15:02.482 DEBUG faker.factory:factory.py:95: Provider `faker.providers.internet` has been localized to `en_US`.
2024-09-10 05:15:02.482 DEBUG faker.factory:factory.py:106: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.482 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.job`.
2024-09-10 05:15:02.484 DEBUG faker.factory:factory.py:95: Provider `faker.providers.job` has been localized to `en_US`.
2024-09-10 05:15:02.484 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.lorem`.
2024-09-10 05:15:02.485 DEBUG faker.factory:factory.py:95: Provider `faker.providers.lorem` has been localized to `en_US`.
2024-09-10 05:15:02.485 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.misc`.
2024-09-10 05:15:02.485 DEBUG faker.factory:factory.py:95: Provider `faker.providers.misc` has been localized to `en_US`.
2024-09-10 05:15:02.485 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.passport`.
2024-09-10 05:15:02.486 DEBUG faker.factory:factory.py:95: Provider `faker.providers.passport` has been localized to `en_US`.
2024-09-10 05:15:02.486 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.person`.
2024-09-10 05:15:02.488 DEBUG faker.factory:factory.py:95: Provider `faker.providers.person` has been localized to `en_US`.
2024-09-10 05:15:02.488 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2024-09-10 05:15:02.490 DEBUG faker.factory:factory.py:95: Provider `faker.providers.phone_number` has been localized to `en_US`.
2024-09-10 05:15:02.491 DEBUG faker.factory:factory.py:106: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.491 DEBUG faker.factory:factory.py:106: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.491 DEBUG faker.factory:factory.py:106: Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.491 DEBUG faker.factory:factory.py:76: Looking for locale `en_US` in provider `faker.providers.ssn`.
2024-09-10 05:15:02.492 DEBUG faker.factory:factory.py:95: Provider `faker.providers.ssn` has been localized to `en_US`.
2024-09-10 05:15:02.492 DEBUG faker.factory:factory.py:106: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2024-09-10 05:15:02.494 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-09-10 05:15:03.089 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "POST /backend/api/deal/create-with-client HTTP/1.1" 200 None
2024-09-10 05:15:03.090 CRITICAL root:helpers_api.py:27: ___response code- 200
2024-09-10 05:15:03.090 CRITICAL root:helpers_api.py:28: ___response body- {'deal_id': 5931}