2024-08-09 05:32:49.673 INFO page_ 1:conftest.py:34: new page opened: [<Page url='about:blank'>]
2024-08-09 05:32:49.680 DEBUG tests_api.utils.logger:logger.py:23: > GET https://dev.agentum.pro/backend/api/deal/kanban?type=rent {'method': 'GET', 'url': 'https://dev.agentum.pro/backend/api/deal/kanban?type=rent', 'params': None, 'headers': {'Authorization': 'Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz'}}
2024-08-09 05:32:49.681 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-08-09 05:32:49.783 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "GET /backend/api/deal/kanban?type=rent HTTP/1.1" 502 157
2024-08-09 05:32:49.784 DEBUG tests_api.utils.logger:logger.py:27: < 502 https://dev.agentum.pro/backend/api/deal/kanban?type=rent <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

2024-08-09 05:32:49.784 DEBUG tests_api.utils.logger:logger.py:35: curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz' -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.31.0' 'https://dev.agentum.pro/backend/api/deal/kanban?type=rent'