2024-08-10 05:32:43.354 INFO page_ 1:conftest.py:34: new page opened: [<Page url='about:blank'>]
2024-08-10 05:32:43.361 DEBUG tests_api.utils.logger:logger.py:23: > PUT https://dev.agentum.pro/backend/api/deal/3044/status {'method': 'PUT', 'url': 'https://dev.agentum.pro/backend/api/deal/3044/status', 'headers': {'Authorization': 'Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz', 'Content-Type': 'application/json'}, 'json': None, 'data': '{"status": "finished_success"}'}
2024-08-10 05:32:43.363 DEBUG urllib3.connectionpool:connectionpool.py:1048: Starting new HTTPS connection (1): dev.agentum.pro:443
2024-08-10 05:32:43.458 DEBUG urllib3.connectionpool:connectionpool.py:546: https://dev.agentum.pro:443 "PUT /backend/api/deal/3044/status HTTP/1.1" 502 157
2024-08-10 05:32:43.459 DEBUG tests_api.utils.logger:logger.py:27: < 502 https://dev.agentum.pro/backend/api/deal/3044/status <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

2024-08-10 05:32:43.459 DEBUG tests_api.utils.logger:logger.py:35: curl -X PUT -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer YwQogs0aDUHzYIgAIN88OBaTDiKesDmAdciD9vkz' -H 'Connection: keep-alive' -H 'Content-Length: 30' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.31.0' -d '{"status": "finished_success"}' https://dev.agentum.pro/backend/api/deal/3044/status